# Site settings
name: WEFT 
title: WEFT 90.1fm
email: bzelip@gmail.com
description: "Community radio based in Champaign-Urbana, Illinois since 1981."
baseurl: ""
url: "http://weftradio.github.io"

# Build settings
markdown: kramdown
permalinks: pretty
